services:
  app:
    image: kcr.karmatek.io/sherlock-app:latest
    restart: unless-stopped
    environment:
      - APP_URL=http://10.162.22.84
      - LOG_LEVEL=debug
      - LOG_CHANNEL=stderr
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=sherlock
      - DB_USERNAME=sherlock
      - DB_PASSWORD=password
    networks:
      - sherlock
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: sherlock
      MYSQL_USER: sherlock
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - sherlock

  nginx:
    image: kcr.karmatek.io/sherlock-proxy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      #    volumes:
      # Optional SSL certificates - uncomment and mount your certificates
      # - ./path/to/your/cert.pem:/etc/nginx/ssl/cert.pem
      # - ./path/to/your/key.pem:/etc/nginx/ssl/key.pem
    networks:
      - sherlock
    depends_on:
      - app

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    networks:
      - sherlock

  websocket:
    image: kcr.karmatek.io/sherlock-websocket:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - sherlock

volumes:
  mysql_data:

networks:
  sherlock:
