services:
  app:
    image: kcr.karmatek.io/sherlock-app:latest
    restart: unless-stopped
    volumes:
      - app_storage:/app/storage
    networks:
      - sherlock

  websocket:
    image: kcr.karmatek.io/sherlock-websocket:latest
    restart: unless-stopped
    networks:
      - sherlock

volumes:
  app_storage:

networks:
  sherlock:
    driver: bridge
