services:
  app:
    image: kcr.karmatek.io/sherlock-app:latest
    restart: unless-stopped
    volumes:
      - app_storage:/app/storage
    networks:
      - sherlock

#  websocket:
#    image: kcr.karmatek.io/sherlock-websocket:latest
#    restart: unless-stopped
#    environment:
#      - REDIS_HOST=redis
#      - REDIS_PORT=6379
#    depends_on:
#      - redis
#    networks:
#      - sherlock

volumes:
  app_storage:

networks:
  sherlock:
    driver: bridge
