services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    restart: unless-stopped
    volumes:
      - ./.env.production:/var/www/.env
    networks:
      - sherlock
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: sherlock
      MYSQL_USER: sherlock
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - sherlock

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "8001:80"
      - "8443:443"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
#      - ./docker/nginx/default-ssl.conf:/etc/nginx/conf.d/default-ssl.conf
#      - ./docker/nginx/ssl/cert.pem:/etc/nginx/ssl/cert.pem
#      - ./docker/nginx/ssl/key.pem:/etc/nginx/ssl/key.pem
    networks:
      - sherlock
    depends_on:
      - app

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - sherlock

volumes:
  mysql_data:

networks:
  sherlock:
